animes/urls.py
# animes/urls.py
# animes/urls.py
from django.contrib import admin
from django.urls import include, path
from core.views import home


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('core/', include('core.urls')),
    path('core/', include('core.urls')),
    
]

core/urls.py
# core/urls.py
from django.urls import path
from .views import random_page,home,search_anime


app_name = 'core'  # Defina o app_name para usar com o namespace

urlpatterns = [
    path('random/', random_page, name='random_page'),
    path('', home, name='home'),
    path('search/', search_anime, name='search_anime'),

]

core/models.py
from django.db import models

class Anime(models.Model):
    title = models.CharField(max_length=255)
    synopsis = models.TextField()
    genre = models.CharField(max_length=100)
    trailer_url = models.URLField(blank=True, null=True)

    def __str__(self):
        return self.title

core/forms.py
# core/forms.py
from django import forms



class AnimeSearchForm(forms.Form):
    query = forms.CharField(
        max_length=100,
        widget=forms.TextInput(attrs={
            'class': 'form-control mr-sm-2',
            'type': 'search',
            'placeholder': 'Search',
            'aria-label': 'Search',
        })
    )

core/views.py
from django.shortcuts import render, redirect
import requests
from googletrans import Translator
from django.http import HttpResponse, HttpResponseServerError
from django.template import loader, TemplateDoesNotExist
from .models import Anime
from .forms import AnimeSearchForm
from .utils import get_top_animes


def random_page(request):
    try:
        api_url = "https://api.jikan.moe/v4/random/anime"
        response = requests.get(api_url)

        if response.status_code == 200:
            data = response.json()

            if data and 'data' in data and 'title' in data['data']:
                translator = Translator()
                raw_synopsis = data['data'].get('synopsis', '')
                
                # Limita a sinopse a 300 caracteres
                max_synopsis_length = 300
                limited_synopsis = raw_synopsis[:max_synopsis_length] + ('...' if len(raw_synopsis) > max_synopsis_length else '')

                translated_synopsis = translator.translate(limited_synopsis, dest='pt').text

                anime, created = Anime.objects.get_or_create(
                    title=data['data']['title'],
                    defaults={'synopsis': translated_synopsis, 'genre': ', '.join(genre['name'] for genre in data['data'].get('genres', [])),
                              'trailer_url': data['data'].get('trailer', {}).get('embed_url', '')}
                )

                animes = Anime.objects.all()

                return render(request, 'core/random_page.html', {'animes': animes, 'image_info': data['data'].get('images', {}),
                                                                'title': data['data'].get('title', ''),
                                                                'synopsis': translated_synopsis,
                                                                'trailer_embed_url': data['data'].get('trailer', {}).get('embed_url', '')})
            else:
                return render(request, 'core/error.html', {'error_message': 'Formato de dados inválido da API'})
        else:
            return render(request, 'core/error.html', {'error_message': 'Falha ao obter dados da API'})
    except Exception as e:
        # Se ocorrer algum erro durante a execução do código
        try:
            # Tenta carregar o template de erro
            error_template = loader.get_template('core/error.html')
            # Se o template existir, renderiza com a mensagem de erro
            return HttpResponseServerError(error_template.render({'error_message': str(e)}))
        except TemplateDoesNotExist:
            # Se o template de erro não existir, fornece uma resposta simples com a mensagem de erro
            return HttpResponseServerError(f"Erro: {str(e)}")


def home(request):
    # Obtém os principais animes usando a função get_top_animes
    top_animes = get_top_animes()

    # Verifique se a chamada à API foi bem-sucedida
    if top_animes and 'data' in top_animes:
        return render(request, 'core/home.html', {'top_animes': top_animes['data']})
    else:
        # Trate o erro de chamada à API de acordo
        return render(request, 'core/error.html', {'error_message': 'Erro ao obter os principais animes'})




def search_anime(request):
    query = request.GET.get('query', '')
    sfw = request.GET.get('sfw', 'true')  # Valor padrão 'true' se não estiver presente
    unapproved = request.GET.get('unapproved', 'false')  # Valor padrão 'false' se não estiver presente

    # Construa a URL da API com os parâmetros da consulta
    api_url = f"https://api.jikan.moe/v4/anime?q={query}&sfw={sfw}&unapproved={unapproved}"

    try:
        response = requests.get(api_url)
        if response.status_code == 200:
            data = response.json()
            return render(request, 'core/search_results.html', {'animes': data.get('data', [])})
        else:
            return render(request, 'core/error.html', {'error_message': 'Falha ao obter dados da API'})
    except Exception as e:
        return render(request, 'core/error.html', {'error_message': str(e)})
    

core/templates/core/base.html
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Anime Base{% endblock %}</title>
    <!-- Adicionando link para o Bootstrap (se não estiver incluído) -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    {% block extra_head %}{% endblock %}
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'core:home' %}">Home</a>
        <a class="navbar-brand" href="{% url 'core:random_page' %}">Random</a>

        <!-- core/templates/core/base.html -->
        <form class="form-inline my-2 my-lg-0" method="get" action="{% url 'core:search_anime' %}">
            {% csrf_token %}
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="query">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
    </nav>

    <div class="container">
        {% block content %}{% endblock %}
    </div>

    <!-- Adicionando script do Bootstrap (se não estiver incluído) -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

core/templates/core/home.html
{% extends 'core/base.html' %}

{% block content %}
  <div class="card mt-4" style="max-width: 600px; margin: auto;">
    <div class="card-body">
      <h2 class="card-title mb-4">Top Animes</h2>

      <div id="carouselTopAnimes" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">
          {% for anime in top_animes %}
            <div class="carousel-item {% if forloop.first %}active{% endif %}">
                <div class="carousel-caption d-none d-md-block">
                    <h5>{{ anime.title }}</h5>
                    <!-- Adicione mais informações conforme necessário -->
                </div>
                <img src="{% if anime.images and anime.images.jpg and anime.images.jpg.image_url %}{{ anime.images.jpg.image_url }}{% else %}{{ your_placeholder_image_url }}{% endif %}" class="d-block w-100 carousel-image" alt="{{ anime.title }}">
            </div>
          {% endfor %}
        </div>
        <!-- Botões de avançar e voltar -->
        <a class="carousel-control-prev" href="#carouselTopAnimes" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselTopAnimes" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>
    </div>
  </div>
{% endblock %}

core/templates/core/random_page.html
{% extends 'core/base.html' %}

{% block title %}Random Page{% endblock %}

{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Detalhes do Anime</title>
    <!-- Adicionando link para o Bootstrap (se não estiver incluído) -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <style>
        /* Estilo personalizado para a página */
        body {
            background: #f8f9fa;  /* Cor de fundo alternativa */
            color: #ffffff;
            margin: auto;
        }

        .container {
            margin-top: 50px;
        }

        .anime-details {
            background-color: rgba(0, 0, 0, 0.7);
            padding: 20px;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            margin-bottom: 20px;
        }

        img {
            max-width: 100%;
            height: auto;
            border-radius: 8px;
        }

        iframe {
            width: 100%;
            height: 400px;
            border-radius: 8px;
        }

        /* Estilos responsivos */
        @media (max-width: 768px) {
            .anime-details {
                padding: 10px;
            }
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-md-6 offset-md-3">
                <div class="card anime-details">
                    <div class="card-body">
                        <h1 class="card-title">{{ title }}</h1>
                        <div class="row">
                            <div class="col-md-6">
                                <!-- Exibindo a imagem -->
                                {% if image_info %}
                                    <img src="{{ image_info.jpg.large_image_url }}" alt="Imagem do Anime" class="img-fluid">
                                {% else %}
                                    <p>Imagem não disponível</p>
                                {% endif %}
                            </div>
                            <div class="col-md-6">
                                <!-- Exibindo a sinopse -->
                                <p class="card-text">{{ synopsis }}</p>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- Exibindo o trailer -->
                {% if trailer_embed_url %}
                    <div class="embed-responsive embed-responsive-16by9 mt-3">
                        <iframe class="embed-responsive-item" src="{{ trailer_embed_url }}" allowfullscreen></iframe>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>

    <!-- Adicionando script do Bootstrap (se não estiver incluído) -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

{% endblock %}

core/templates/core/search_results.html
{% extends 'core/base.html' %}

{% block title %}Search Results{% endblock %}

{% block content %}
    <h2 class="mb-4">Search Results</h2>
    <div class="row">
        {% if animes %}
            {% for anime in animes %}
                <div class="col-md-4 mb-4">
                    <div class="card h-100">
                        {% if anime.images and anime.images.jpg and anime.images.jpg.small_image_url %}
                            <img src="{{ anime.images.jpg.small_image_url }}" class="card-img-top" alt="{{ anime.title }}">
                        {% endif %}
                        <div class="card-body">
                            <h5 class="card-title">{{ anime.title }}</h5>
                            {% if anime.synopsis %}
                                <p class="card-text">{{ anime.synopsis|slice:":300" }}</p>
                            {% else %}
                                <p class="card-text">No synopsis available.</p>
                            {% endif %}
                        </div>
                    </div>
                </div>
            {% endfor %}
        {% else %}
            <div class="col">
                <p>No results found.</p>
            </div>
        {% endif %}
    </div>
{% endblock %}